LearningCloud.MVC/Areas/Admin/ViewModels/AulaViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LearningCloud.Domain.Entities;
using System.Collections.Generic;
using System.Web.Mvc;

namespace LearningCloud.MVC.Areas.Admin.ViewModels
{
    public class AulaViewModel : IValidatableObject
    {
        [Key]
        public int Aula_Id { get; set; }

        [Required(ErrorMessage = "Preencha o campo Título.")]
        [StringLength(200, ErrorMessage = "O {0} deve possuir no mínimo {2} e máximo {1} caracteres.", MinimumLength = 2)]
        [DisplayName("Título")]
        public string Aula_Titulo { get; set; }

        [DisplayName("Tipo Conteúdo")]
        [Required(ErrorMessage = "Informe o tipo do conteúdo.")]
        public string aul_tipoconteudo { get; set; }

        [Required(ErrorMessage = "Preencha o campo Introdução.")]
        [StringLength(8000, ErrorMessage = "O {0} deve possuir no mínimo {2} e máximo {1} caracteres.", MinimumLength = 2)]
        [AllowHtml]
        [DisplayName("Introdução")]
        public string aul_indroducao { get; set; }

        [Required(ErrorMessage = "Preencha o campo Descrição.")]
        [StringLength(8000, ErrorMessage = "O {0} deve possuir no mínimo {2} e máximo {1} caracteres.", MinimumLength = 2)]
        [AllowHtml]
        [DisplayName("Descrição")]
        public string aul_descricao { get; set; }

        [AllowHtml]
        [DisplayName("Pré-requisitos")]
        public string aul_prerequisitos { get; set; }
        
        //[DisplayName("Imagem")]
        //public string aul_imagem { get; set; }

        [DisplayName("Tempo do Vídeo")]
        public string aul_tempovideo { get; set; }

        [DisplayName("Vídeo")]
        public string aul_video { get; set; }

        [AllowHtml]
       // [Column(TypeName = "varchar(MAX)"), MaxLength]
        [DisplayName("Conteúdo Artigo")]
        public string aul_conteudoartigo { get; set; }

        [DisplayName("Palavras Chave")]
        public string aul_palavraschave { get; set; }

        [DisplayName("Status")]
        [Column(TypeName = "char")]
        [Required(ErrorMessage = "Informe o status da aula.")]
        public string aul_status { get; set; }

        [Required(ErrorMessage = "Selecione o nível de disponibilidade.")]
        [DisplayName("Disponível a partir")]
        public int aul_fk_assinaturanivel { get; set; }

        public virtual AssinaturaNivel aul_assinaturanivel { get; set; }

        [ScaffoldColumn(false)]
        public DateTime Aula_DataCadastro { get; set; }

        [ScaffoldColumn(false)]
        public DateTime? Aula_DataAlteracao { get; set; }


        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (aul_tipoconteudo == "V" && (string.IsNullOrEmpty(aul_video) || string.IsNullOrEmpty(aul_tempovideo)))
            {
                yield return new ValidationResult("Preenha os campos obrigatórios na aba Videoaula.");

                if (aul_tipoconteudo == "V" && string.IsNullOrEmpty(aul_video))
                    yield return new ValidationResult("Adicione o vídeo.", new string[] { "aul_video" });

                if (aul_tipoconteudo == "V" && string.IsNullOrEmpty(aul_tempovideo))
                {
                    yield return new ValidationResult("Informe o tempo do vídeo.", new string[] { "aul_tempovideo" });
                }
            }

            if (string.IsNullOrEmpty(aul_indroducao))
            {
                yield return new ValidationResult("Preenha o campo obrigatório na aba Introdução.");
            }

            if (string.IsNullOrEmpty(aul_descricao))
            {
                yield return new ValidationResult("Preenha o campo obrigatório na aba Descrição.");
            }

            if (aul_tipoconteudo == "A" && string.IsNullOrEmpty(aul_conteudoartigo)) { 
                yield return new ValidationResult("Preenha os campos obrigatórios na aba Artigo.");
                yield return new ValidationResult("Informe o conteúdo do artigo.", new string[] { "aul_conteudoartigo" });
            }
        }

    }
}

LearningCloud.MVC/Areas/Admin/Controllers/AulaController.cs
using System.Web.Mvc;
using System.Collections.Generic;
using AutoMapper;
using PagedList;
using LearningCloud.Application.Interfaces;
using LearningCloud.Domain.Entities;
using LearningCloud.MVC.Areas.Admin.ViewModels;
using System.Web;
using System;
using System.IO;
using System.Net;


namespace LearningCloud.MVC.Areas.Admin.Controllers
{
    [Authorize]
    public class AulaController : Controller
    {
        private readonly IAulaAppService _aulaApp;
        private readonly IAssinaturaNivelAppService _assinaturaNivelApp;
        
        public AulaController(IAulaAppService aulaApp, IAssinaturaNivelAppService assinaturaNivelApp)
        {
            _aulaApp = aulaApp;
            _assinaturaNivelApp = assinaturaNivelApp;
        }

        // GET: Admin/Aula
        public ActionResult Index(int? page)
        {
            int paginaTamanho = 2;
            int paginaNumero = (page ?? 1);

            var aulaViewModel = Mapper.Map<IEnumerable<Aula>, IEnumerable<AulaViewModel>>(_aulaApp.GetAll());

            ViewBag.page = page;

            return View(aulaViewModel.ToPagedList(paginaNumero, paginaTamanho));
        }

        // GET: Admin/Aula/Details/5
        public ActionResult Details(int id, int? page)
        {
            var aula = _aulaApp.GetById(id);
            var aulaViewModel = Mapper.Map<Aula, AulaViewModel>(aula);

            ViewBag.page = page;

            return View(aulaViewModel);
        }

        // GET: Admin/Aula/Create
        public ActionResult Create(int? page)
        {
            ViewBag.assinaturanivel = new SelectList(_assinaturaNivelApp.GetByStatusAssinaturaNivel("A"), "AssinaturaNivel_Id", "asn_titulo");
            ViewBag.page = page;

            return View();
        }

        // POST: Admin/Aula/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AulaViewModel aula, int? page)
        {
            if (ModelState.IsValid)
            {
                var aulaDomain = Mapper.Map<AulaViewModel, Aula>(aula);

                _aulaApp.CreateAula(aulaDomain);

                return RedirectToAction("Index");
            }

            ViewBag.assinaturanivel = new SelectList(_assinaturaNivelApp.GetByStatusAssinaturaNivel("A"), "AssinaturaNivel_Id", "asn_titulo", aula.aul_fk_assinaturanivel);
            ViewBag.page = page;

            return View(aula);
        }

        // GET: Admin/Aula/Edit/5
        public ActionResult Edit(int id, int? page, string returnaction)
        {
            var aula = _aulaApp.GetById(id);
            var aulaViewModel = Mapper.Map<Aula, AulaViewModel>(aula);

            if (returnaction == "" || returnaction == null)
            {
                returnaction = "Index";
            }

            ViewBag.assinaturanivel = new SelectList(_assinaturaNivelApp.GetByStatusAssinaturaNivel("A"), "AssinaturaNivel_Id", "asn_titulo", aulaViewModel.aul_fk_assinaturanivel);
            ViewBag.page = page;
            ViewBag.ReturnAction = returnaction;

            return View(aulaViewModel);

        }

        // POST: Admin/Aula/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AulaViewModel aula, int? page, string returnaction)
        {
            if (ModelState.IsValid)
            {
                var aulaDomain = Mapper.Map<AulaViewModel, Aula>(aula);

                _aulaApp.UpdateAula(aulaDomain);

                return RedirectToAction((string)returnaction, new { page = page });
            }

            ViewBag.assinaturanivel = new SelectList(_assinaturaNivelApp.GetByStatusAssinaturaNivel("A,I"), "AssinaturaNivel_Id", "asn_titulo", aula.aul_fk_assinaturanivel);
            ViewBag.page = page;
            ViewBag.ReturnAction = returnaction;

            return View(aula);

        }

        // GET: Admin/Aula/Delete/5
        public ActionResult Delete(int id, int? page)
        {
            var aula = _aulaApp.GetById(id);
            var aulaViewModel = Mapper.Map<Aula, AulaViewModel>(aula);

            ViewBag.page = page;

            return View(aulaViewModel);

        }

        // POST: Admin/Aula/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var aula = _aulaApp.GetById(id);

            _aulaApp.RemoveAula(aula);

            return RedirectToAction("Index");
        }

        // GET: Aula/Inactivate/5
        public ActionResult Inactivate(int id, int? page)
        {
            var aula = _aulaApp.GetById(id);
            var aulaViewModel = Mapper.Map<Aula, AulaViewModel>(aula);

            ViewBag.page = page;

            return View(aulaViewModel);
        }

        // POST: Aula/Inactivate/5
        [HttpPost, ActionName("Inactivate")]
        [ValidateAntiForgeryToken]
        public ActionResult InactivateConfirmed(int id, int? page)
        {
            var aula = _aulaApp.GetById(id);

            _aulaApp.ChangeStatusAula(aula, "I");

            return RedirectToAction("Index", new { page = page });
        }

        // GET: Aula/Activate/5
        public ActionResult Activate(int id, int? page)
        {
            var aula = _aulaApp.GetById(id);

            _aulaApp.ChangeStatusAula(aula, "A");

            return RedirectToAction("Index", new { page = page });
        }

       

        [HttpPost]
        public JsonResult AdicionarVideo(HttpPostedFileBase filevideo)
        {

            string resultadoUpImagem = null;
         
            try
            {

                
                if (filevideo != null)
                {
                    string fileExt = Path.GetExtension(filevideo.FileName).Replace(@".", @"").ToLower();

                    if (filevideo.ContentLength > 0)
                    {
                         if (fileExt != "mp4" && fileExt != "webm" && fileExt != "mkv")
                        {
                            //  Response.Status = "804 Tipo de arquivo não permitido";
                            Response.Status = "804 Tipo de arquivo não permitido.  <br />Selecione apenas arquivos de video (.mp4, .webm ou .mkv). ";

                        }
                        else
                        {
                            //var v = file.ContentLength;
                            //if (file.ContentLength > 3145728)  //3145728  bytes  = 3 Mb
                            //{
                            //    ViewBag.Message = "O Tamanho do arquivo não permitido. <br />Selecione um video de até 3Mb";
                            //    ViewBag.Status = -1;
                            //    return PartialView();
                            //}
                            //else
                            //{
                                resultadoUpImagem = UploadVideoaula.UploadFileVideoaula(filevideo);

                                
                            //}
                        }
                    }
                    else
                    {
                        Response.Status = "802 O Conteudo do Arquivo está vazio. ";

                    }
                }
                else
                {
                    Response.Status = "803 O Arquivo é nullo.";

                }
            }
            catch (WebException e)
            {
                resultadoUpImagem = e.Response.ToString();
            }

            return Json(resultadoUpImagem);

        }

    }
}

LearningCloud.MVC/Areas/Admin/Views/Aula/Delete.cshtml
@model LearningCloud.MVC.Areas.Admin.ViewModels.AulaViewModel

@{
    ViewBag.Title = "Excluir Aula";
}

<section class="content-header">
    <h1> Excluir Aula <small>Tem certeza que gostaria de excluir essa aula?</small> </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Aula</h3>
        </div>

        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div>

                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Aula_Titulo)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Aula_Titulo)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_tipoconteudo)
                            </dt>

                            <dd>
                                @if (Model.aul_tipoconteudo == "V")
                                {
                                    <span>Videoaula</span>
                                }
                                else if (Model.aul_tipoconteudo == "A")
                                {
                                    <span>Artigo</span>
                                }
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_indroducao)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_indroducao)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_descricao)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_descricao)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_prerequisitos)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_prerequisitos)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_imagem)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_imagem)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_tempovideo)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_tempovideo)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_video)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_video)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_conteudoartigo)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_conteudoartigo)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_palavraschave)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_palavraschave)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_status)
                            </dt>

                            <dd>
                                @if (Model.aul_status == "A")
                                {
                                    <span>Ativo</span>
                                }
                                else if (Model.aul_status == "I")
                                {
                                    <span>Inativo</span>
                                }
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_fk_assinaturanivel)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_assinaturanivel.asn_titulo)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-default" /> |
                                @Html.ActionLink("Voltar", "Index", new { page = ViewBag.page })
                            </div>
                        }
                    </div>
                </div> <!-- /.col-md-12 -->
            </div><!-- /.row -->
            <div class="box-footer">

            </div><!-- /.box-footer -->
        </div><!-- /.box-body -->
    </div><!-- /.box box-default -->
</section><!-- /.content -->

LearningCloud.MVC/Areas/Admin/Views/Aula/Details.cshtml
@model LearningCloud.MVC.Areas.Admin.ViewModels.AulaViewModel

@{
    ViewBag.Title = "Detalhes";
}
<section class="content-header">
    <h1> Detalhes Aula <small>@Model.Aula_Titulo </small> </h1>
</section>
<!-- Main content -->
<section class="content">
    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Aula</h3>
        </div>

        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div>
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Aula_Titulo)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Aula_Titulo)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_tipoconteudo)
                            </dt>

                            <dd>
                                @if (Model.aul_tipoconteudo == "V")
                                {
                                    <span>Videoaula</span>
                                }
                                else if (Model.aul_tipoconteudo == "A")
                                {
                                    <span>Artigo</span>
                                }
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_indroducao)
                            </dt>

                            <dd>
                                @Html.Raw(Model.aul_indroducao)
                                @*@Html.DisplayFor(model => model.aul_indroducao)*@
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_descricao)
                            </dt>

                            <dd>
                                @Html.Raw(Model.aul_descricao)
                                @*@Html.DisplayFor(model => model.aul_descricao)*@
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_prerequisitos)
                            </dt>

                            <dd>
                                @Html.Raw(Model.aul_prerequisitos)
                                @*@Html.DisplayFor(model => model.aul_prerequisitos)*@
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_tempovideo)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_tempovideo)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_video)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_video)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_conteudoartigo)
                            </dt>

                            <dd>
                                @Html.Raw(Model.aul_conteudoartigo)
                                @*@Html.DisplayFor(model => model.aul_conteudoartigo)*@
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_palavraschave)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_palavraschave)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_status)
                            </dt>

                            <dd>
                                @if (Model.aul_status == "A")
                                {
                                    <span>Ativo</span>
                                }
                                else if (Model.aul_status == "I")
                                {
                                    <span>Inativo</span>
                                }
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.aul_fk_assinaturanivel)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.aul_assinaturanivel.asn_titulo)
                            </dd>

                        </dl>
                    </div>
                    <p>
                        @Html.ActionLink("Alterar", "Edit", new { id = Model.Aula_Id, page = ViewBag.page, returnaction = "Details/" + Model.Aula_Id }) <label>|</label>
                        @Html.ActionLink("Voltar", "Index", new { page = ViewBag.page })
                    </p>
                </div> <!-- /.col-md-12 -->
            </div><!-- /.row -->
            <div class="box-footer">

            </div><!-- /.box-footer -->
        </div><!-- /.box-body -->
    </div><!-- /.box box-default -->
</section><!-- /.content -->

LearningCloud.MVC/Areas/Admin/Views/Aula/Index.cshtml
@model IPagedList<LearningCloud.MVC.Areas.Admin.ViewModels.AulaViewModel>
@using PagedList;
@using PagedList.Mvc;
@using LearningCloud.MVC.HTMLHelpers;

@{
    ViewBag.Title = "Consultar Aulas";
    string classeCssInativo = "";
}

<section class="content-header">
    <h1> Consulta de Aulas <small>Todas as aulas</small> </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
        <li class="active">Here</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Aula</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <p>
                                <a href="@Url.Action("Create", new { page = ViewBag.page })" data-toggle="tooltip" data-placement="right" title="Cadastrar Nova Aula"><i class="fa fa-file-video-o">&nbsp;</i>Nova Aula</a>
                            </p>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="nav navbar-nav navbar-right" style="color:#006A5A; font-weight:bold; font-size:12px; border: 1px solid #fff; background-color: #ecf0f5;">
                                @*
                                    @Model.PageCount <span>PageCount</span><br />
                                    @Model.TotalItemCount <span>TotalItemCount</span><br />
                                    @Model.PageNumber <span>PageNumber</span><br />
                                    @Model.PageSize <span>PageSize</span><br />
                                *@

                                @Html.LegendaPaginacao("Videoaula", 'F', null, Model.PageNumber, Model.PageSize, Model.TotalItemCount)
                            </div>
                        </div>
                    </div>
                    <table class="table table-condensed table-striped">
                        <tr>
                            <th width="35%">Título</th>
                            <th width="7%">Tipo Conteúdo</th>
                            <th width="37%">Curso</th>
                            @*<th>Introdução</th>
                            <th>Descrição</th>
                            <th>Pré-requisitos</th>
                            <th>Tempo do Vídeo</th>
                            <th>Vídeo</th>
                            <th>Conteúdo Artigo</th>
                            <th>Palavras Chave</th>*@
                            <th width="5%">Status</th>
                            <th width="10%">Disponível a partir de</th>
                            <th width="6%"></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            classeCssInativo = "";

                            if (item.aul_status == "I")
                            {
                                classeCssInativo = "warning";
                            }
                            <tr class="@classeCssInativo">

                                <td>
                                    @Html.DisplayFor(modelItem => item.Aula_Titulo)
                                </td>
                                <td>
                                    @if (item.aul_tipoconteudo == "V")
                                    {
                                        <span>Videoaula </span>
                                    }
                                    else if (item.aul_tipoconteudo == "A")
                                    {
                                        <span>Artigo</span>
                                    }
                                </td>
                                <td>
                                    Não definido
                                </td>
                                @*<td>
                                    @Html.DisplayFor(modelItem => item.aul_indroducao)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.aul_descricao)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.aul_prerequisitos)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.aul_tempovideo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.aul_video)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.aul_conteudoartigo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.aul_palavraschave)
                                </td>*@
                                <td>
                                    @if (item.aul_status == "A")
                                    {
                                        <span>Ativo</span>
                                    }
                                    else if (item.aul_status == "I")
                                    {
                                        <span>Inativo</span>
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.aul_assinaturanivel.asn_titulo)
                                </td>
                                <td class="td_toolIcons">
                                    <a href="@Url.Action("Details", new { id = item.Aula_Id, page = ViewBag.page })" data-toggle="tooltip" data-placement="top" title="Detalhes"><i class="fa fa-ellipsis-h"></i></a><label>&nbsp;</label>
                                    <a href="@Url.Action("Edit", new { id = item.Aula_Id, page = ViewBag.page })" data-toggle="tooltip" data-placement="top" title="Alterar"><i class="fa fa-pencil-square-o"></i></a><label>&nbsp;</label>
                                    <a href="@Url.Action("Delete", new { id = item.Aula_Id, page = ViewBag.page })" data-toggle="tooltip" data-placement="top" title="Excluir"><i class="fa fa-trash-o"></i></a>
                                    @if (item.aul_status == "A")
                                    {
                                        <label>&nbsp;</label>  
                                        <a href="@Url.Action("Inactivate", new { id = item.Aula_Id, page = ViewBag.page })" data-toggle="tooltip" data-placement="top" title="Inativar"><i class="fa fa-check-square-o"></i></a>
                                    }
                                    else if (item.aul_status == "I")
                                    {
                                        <label>&nbsp;</label>  
                                        <a href="@Url.Action("Activate", new { id = item.Aula_Id, page = ViewBag.page })" data-toggle="tooltip" data-placement="top" title="Ativar"><i class="fa fa-square-o"></i></a>
                                    }
                                </td>
                            </tr>
                        }

                    </table>
                    <div class="row" style=" text-align:center">
                        <div class="col-md-12">
                            @Html.PagedListPager(Model, page => Url.Action("Index", "Aula", new { page }))
                        </div>
                    </div>
                </div> <!-- /.col-md-12 -->
            </div><!-- /.row -->
        </div><!-- /.box-body -->
    </div><!-- /.box box-default -->
</section><!-- /.content -->